version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps/nuget):"
    labels:
      - "type:dependabot"
      - "type:dependencies-nuget"
      
 - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps/github-actions):"
    labels:
      - "type:dependabot"
      - "type:dependencies-github-actions"
